Repository args06/Digimind, pull requests merged in 2024-05, with the labels that each got.

#1 chore(architecture): Add icon, color assets, localizable
  MiniKita.xcodeproj/project.pbxproj
  MiniKita.xcodeproj/project.xcworkspace/xcuserdata/anjarharimurti.xcuserdatad/UserInterfaceState.xcuserstate
  MiniKita.xcodeproj/xcuserdata/anjarharimurti.xcuserdatad/xcschemes/xcschememanagement.plist
  MiniKita/Assets.xcassets/AppIcon.appiconset/Contents.json
  MiniKita/Assets.xcassets/AppIcon.appiconset/appIcon.png
  MiniKita/Assets.xcassets/Color/AlloyOrange.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/AmaranthDeepPurple.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/AntiFlashWhite.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/CarrotOrange.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/Contents.json
  MiniKita/Assets.xcassets/Color/GhostWhite.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/GraniteGray.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/JungleGreen.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/LightGrey.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/MaximumBlueGreen.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/MetallicOrange.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/Onyx.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/PeachOrange.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/PhillipineGray.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/Platinum.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/RaisinBlack.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/RoseGarnet.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/RoyalRed.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/Silver Foil.colorset/Contents.json
  MiniKita/Helper/en.lproj/Localizable.strings
Labels: feat

#3 style(splash): Create Splash Screen
  MiniKita.xcodeproj/project.pbxproj
  MiniKita.xcodeproj/project.xcworkspace/xcuserdata/esthergabrieltrivena.xcuserdatad/UserInterfaceState.xcuserstate
  MiniKita.xcodeproj/xcuserdata/esthergabrieltrivena.xcuserdatad/xcschemes/xcschememanagement.plist
  MiniKita/Assets.xcassets/splash.imageset/Contents.json
  MiniKita/Assets.xcassets/splash.imageset/splash.png
  MiniKita/MiniKitaApp.swift
  MiniKita/View/Splash/SplashScreen.swift
Labels: style

#4 style(dashboard): Create UI for dashboard
  MiniKita.xcodeproj/project.pbxproj
  MiniKita.xcodeproj/project.xcworkspace/xcuserdata/anjarharimurti.xcuserdatad/UserInterfaceState.xcuserstate
  MiniKita/Assets.xcassets/Color/CoralRed.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/IguanaGreen.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/LightGreens.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/PersianRed.colorset/Contents.json
  MiniKita/Assets.xcassets/Color/Rajah.colorset/Contents.json
  MiniKita/Assets.xcassets/bg_dashboard.imageset/Contents.json
  MiniKita/Assets.xcassets/bg_dashboard.imageset/bg_dashboard.png
  MiniKita/Assets.xcassets/carb.imageset/Contents.json
  MiniKita/Assets.xcassets/carb.imageset/carb.png
  MiniKita/Assets.xcassets/fat.imageset/Contents.json
  MiniKita/Assets.xcassets/fat.imageset/fat.png
  MiniKita/Assets.xcassets/fiber.imageset/Contents.json
  MiniKita/Assets.xcassets/fiber.imageset/fiber.png
  MiniKita/Assets.xcassets/monster.imageset/Contents.json
  MiniKita/Assets.xcassets/monster.imageset/monster.png
  MiniKita/Assets.xcassets/monster_gray.imageset/Contents.json
  MiniKita/Assets.xcassets/monster_gray.imageset/monster_gray.png
  MiniKita/Assets.xcassets/protein.imageset/Contents.json
  MiniKita/Assets.xcassets/protein.imageset/protein.png
  MiniKita/Helper/Util.swift
  MiniKita/MiniKitaApp.swift
  MiniKita/Model/Enum/CalorieCondition.swift
  MiniKita/View/Dashboard/Dashboard.swift
  MiniKita/View/Reusable/NutritionButton.swift
  MiniKita/View/Reusable/ProgressBar.swift
  MiniKita/View/Reusable/WaterWave.swift
  MiniKita/View/Splash/SplashScreen.swift
Labels: style

#5 style(intake): Create form to add ingredient
  .DS_Store
  MiniKita.xcodeproj/project.pbxproj
  MiniKita.xcodeproj/project.xcworkspace/xcuserdata/anjarharimurti.xcuserdatad/UserInterfaceState.xcuserstate
  MiniKita.xcodeproj/project.xcworkspace/xcuserdata/esthergabrieltrivena.xcuserdatad/UserInterfaceState.xcuserstate
  MiniKita/Assets.xcassets/full.imageset/Contents.json
  MiniKita/Assets.xcassets/full.imageset/full.png
  MiniKita/Assets.xcassets/ngintip.imageset/Contents.json
  MiniKita/Assets.xcassets/ngintip.imageset/ngintip.png
  MiniKita/Assets.xcassets/olahan.imageset/Contents.json
  MiniKita/Assets.xcassets/olahan.imageset/olahan.png
  MiniKita/Helper/ViewExtension.swift
  MiniKita/View/Challenge Flow/CollapsibleView.swift
  MiniKita/View/Challenge Flow/CollapsibleWheelPicker.swift
  MiniKita/View/Challenge Flow/FoodUnits.swift
  MiniKita/View/Challenge Flow/FoodUnitsPicker.swift
  MiniKita/View/Challenge Flow/IngredientAmountPage.swift
  MiniKita/View/Challenge Flow/IngredientPartPage.swift
  MiniKita/View/Challenge Flow/IngredientsPage.swift
  MiniKita/View/Challenge Flow/ProcessingPage.swift
  MiniKita/View/Challenge Flow/SwiftUIView5.swift
  MiniKita/View/Dashboard/Dashboard.swift
  MiniKita/View/Reusable/LongButton.swift
  MiniKita/View/Reusable/ProgressBar.swift
  MiniKita/View/Reusable/SpeechBubble.swift
  MiniKita/View/Reusable/SpeechBubble2.swift
Labels: style

#6 feat(data-management): Create Data Management and Wiring data to UI
  MiniKita.xcodeproj/project.pbxproj
  MiniKita.xcodeproj/project.xcworkspace/xcuserdata/anjarharimurti.xcuserdatad/UserInterfaceState.xcuserstate
  MiniKita.xcodeproj/xcuserdata/anjarharimurti.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  MiniKita/Assets.xcassets/badge.imageset/Contents.json
  MiniKita/Assets.xcassets/badge.imageset/badge.png
  MiniKita/Assets.xcassets/full.imageset/full.png
  MiniKita/Assets.xcassets/monster_complete.imageset/Contents.json
  MiniKita/Assets.xcassets/monster_complete.imageset/monster_complete.png
  MiniKita/Assets.xcassets/monster_complete_gray.imageset/Contents.json
  MiniKita/Assets.xcassets/monster_complete_gray.imageset/monster_complete_gray.png
  MiniKita/Assets.xcassets/monster_full.imageset/Contents.json
  MiniKita/Assets.xcassets/monster_full.imageset/monster_full.png
  MiniKita/Assets.xcassets/monster_full_gray.imageset/Contents.json
  MiniKita/Assets.xcassets/monster_full_gray.imageset/monster_full_gray.png
  MiniKita/Data/Enum/ActivityLevel.swift
  MiniKita/Data/Enum/CalorieCondition.swift
  MiniKita/Data/Enum/Gender.swift
  MiniKita/Data/Enum/NutritionType.swift
  MiniKita/Data/Enum/Unit.swift
  MiniKita/Data/Model/FoodUnit.swift
  MiniKita/Data/Model/Ingredient.swift
  MiniKita/Data/Model/IngredientPart.swift
  MiniKita/Data/Model/IngredientWrapper.swift
  MiniKita/Data/Model/ModelData.swift
  MiniKita/Data/Model/Nutrition.swift
  MiniKita/Data/Model/NutritionDetail.swift
  MiniKita/Data/Model/NutritionInfo.swift
  MiniKita/Data/Model/User.swift
  MiniKita/Data/UserDefault/UserDefaultKey.swift
  MiniKita/Helper/DateExtension.swift
  MiniKita/Helper/Util.swift
  MiniKita/Model/Enum/CalorieCondition.swift
  MiniKita/View/Challenge Flow/IngredientAmountPage.swift
  MiniKita/View/Challenge Flow/IngredientPartPage.swift
  MiniKita/View/Challenge Flow/IngredientsPage.swift
  MiniKita/View/Challenge Flow/ProcessingPage.swift
  MiniKita/View/Dashboard/Dashboard.swift
  MiniKita/View/Reusable/FoodUnitsPicker.swift
  MiniKita/View/Reusable/NutritionButton.swift
  MiniKita/View/Splash/SplashScreen.swift
  MiniKita/ViewModel/IntakeViewModel.swift
  MiniKita/ingredientData.json
Labels: feat

#7 refactor(dashboard): Fix condition when full
  MiniKita.xcodeproj/project.xcworkspace/xcuserdata/anjarharimurti.xcuserdatad/UserInterfaceState.xcuserstate
  MiniKita/View/Dashboard/Dashboard.swift
Labels: refactor

#8 feat(dashboard): Create Recap, Profile, and Info Page
  MiniKita.xcodeproj/project.pbxproj
  MiniKita.xcodeproj/project.xcworkspace/xcuserdata/anjarharimurti.xcuserdatad/UserInterfaceState.xcuserstate
  MiniKita.xcodeproj/xcuserdata/anjarharimurti.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  MiniKita/Assets.xcassets/calorie.imageset/Contents.json
  MiniKita/Assets.xcassets/calorie.imageset/calorie.png
  MiniKita/Assets.xcassets/monster_loading.imageset/Contents.json
  MiniKita/Assets.xcassets/monster_loading.imageset/monster_loading.png
  MiniKita/Assets.xcassets/ngintip2.imageset/Contents.json
  MiniKita/Assets.xcassets/ngintip2.imageset/ngintip2.png
  MiniKita/Assets.xcassets/orange.imageset/Contents.json
  MiniKita/Assets.xcassets/orange.imageset/orange.png
  MiniKita/Assets.xcassets/popup_complete.imageset/Contents.json
  MiniKita/Assets.xcassets/popup_complete.imageset/popup_complete.png
  MiniKita/Assets.xcassets/popup_full.imageset/Contents.json
  MiniKita/Assets.xcassets/popup_full.imageset/popup_full.png
  MiniKita/Data/Enum/InformationType.swift
  MiniKita/View/Challenge Flow/IngredientPartPage.swift
  MiniKita/View/Challenge Flow/IngredientsPage.swift
  MiniKita/View/Challenge Flow/ProcessingPage.swift
  MiniKita/View/Dashboard/Dashboard.swift
  MiniKita/View/Dashboard/InformationPage.swift
  MiniKita/View/Dashboard/ProfilePage.swift
  MiniKita/View/Dashboard/RecapDetailPage.swift
  MiniKita/View/Dashboard/RecapPage.swift
  MiniKita/View/Reusable/CustomDialog.swift
  MiniKita/View/Reusable/DetailInformation.swift
  MiniKita/View/Reusable/HistoryCard.swift
  MiniKita/View/Reusable/LongButton.swift
  MiniKita/View/Reusable/NutritionButton.swift
  MiniKita/View/Reusable/RecapBadge.swift
  MiniKita/View/Reusable/RecapHistory.swift
  MiniKita/View/Splash/SplashScreen.swift
  MiniKita/ViewModel/IntakeViewModel.swift
Labels: feat

#9 feat(on-board): Create OnBoard Flow
  MiniKita.xcodeproj/project.pbxproj
  MiniKita.xcodeproj/project.xcworkspace/xcuserdata/esthergabrieltrivena.xcuserdatad/UserInterfaceState.xcuserstate
  MiniKita.xcodeproj/xcuserdata/esthergabrieltrivena.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  MiniKita/Data/Enum/ActivityLevel.swift
  MiniKita/Data/Enum/ActivityMinute.swift
  MiniKita/Helper/Util.swift
  MiniKita/View/OnBoard/ActivityLevel3.swift
  MiniKita/View/OnBoard/ActivityLevelPage.swift
  MiniKita/View/OnBoard/ActivityLevelPage2.swift
  MiniKita/View/OnBoard/ActivityLevelPage3.swift
  MiniKita/View/OnBoard/AllergiesPage.swift
  MiniKita/View/OnBoard/DislikePage.swift
  MiniKita/View/OnBoard/PersonalInfoPage.swift
  MiniKita/View/OnBoard/ProcessingInfoPage.swift
  MiniKita/View/OnBoard/SummaryPersonalInfoPage.swift
  MiniKita/View/OnBoard/WelcomePage.swift
Labels: feat

#10 Feat (Onboard) : add form validation
  MiniKita.xcodeproj/project.xcworkspace/xcuserdata/esthergabrieltrivena.xcuserdatad/UserInterfaceState.xcuserstate
  MiniKita/View/Dashboard/Dashboard.swift
  MiniKita/View/OnBoard/ActivityLevelPage.swift
  MiniKita/View/OnBoard/ActivityLevelPage2.swift
  MiniKita/View/OnBoard/AllergiesPage.swift
  MiniKita/View/OnBoard/DislikePage.swift
  MiniKita/View/OnBoard/PersonalInfoPage.swift
  MiniKita/View/OnBoard/ProcessingInfoPage.swift
  MiniKita/View/OnBoard/SummaryPersonalInfoPage.swift
  MiniKita/View/OnBoard/WelcomePage.swift
  MiniKita/View/Splash/SplashScreen.swift
Labels: feat

#11 feat(swift-data): Data Management and Wiring UI
  MiniKita.xcodeproj/project.pbxproj
  MiniKita.xcodeproj/project.xcworkspace/xcuserdata/anjarharimurti.xcuserdatad/UserInterfaceState.xcuserstate
  MiniKita.xcodeproj/xcuserdata/anjarharimurti.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  MiniKita/.DS_Store
  MiniKita/Data/Entity/Challenge.swift
  MiniKita/Data/Entity/DailyIntake.swift
  MiniKita/Data/Enum/ActivityOften.swift
  MiniKita/Data/Model/FoodUnit.swift
  MiniKita/Data/Model/NutritionInfo.swift
  MiniKita/Data/UserDefault/UserDefaultKey.swift
  MiniKita/Helper/ArrayExtension.swift
  MiniKita/Helper/Util.swift
  MiniKita/MiniKitaApp.swift
  MiniKita/View/Challenge Flow/IngredientAmountPage.swift
  MiniKita/View/Challenge Flow/IngredientsPage.swift
  MiniKita/View/Dashboard/Dashboard.swift
  MiniKita/View/Dashboard/ProfilePage.swift
  MiniKita/View/Dashboard/RecapDetailPage.swift
  MiniKita/View/Dashboard/RecapPage.swift
  MiniKita/View/OnBoard/ActivityLevelPage.swift
  MiniKita/View/OnBoard/ActivityLevelPage2.swift
  MiniKita/View/OnBoard/ActivityLevelPage3.swift
  MiniKita/View/OnBoard/AllergiesPage.swift
  MiniKita/View/OnBoard/DislikePage.swift
  MiniKita/View/OnBoard/PersonalInfoPage.swift
  MiniKita/View/OnBoard/ProcessingInfoPage.swift
  MiniKita/View/OnBoard/SummaryPersonalInfoPage.swift
  MiniKita/View/OnBoard/WelcomePage.swift
  MiniKita/View/Reusable/DetailInformation.swift
  MiniKita/View/Reusable/NutritionButton.swift
  MiniKita/View/Reusable/RecapHistory.swift
  MiniKita/View/Splash/SplashScreen.swift
  MiniKita/ViewModel/IntakeViewModel.swift
  MiniKita/ingredientData.json
Labels: feat

#12 bugfix(intake): Fix full condition
  MiniKita.xcodeproj/project.xcworkspace/xcuserdata/anjarharimurti.xcuserdatad/UserInterfaceState.xcuserstate
  MiniKita.xcodeproj/xcuserdata/anjarharimurti.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  MiniKita/View/Challenge Flow/IngredientAmountPage.swift
  MiniKita/View/Challenge Flow/IngredientsPage.swift
  MiniKita/View/Challenge Flow/ProcessingPage.swift
  MiniKita/View/Dashboard/Dashboard.swift
  MiniKita/View/Reusable/CustomDialog.swift
Labels: bug

#13 bugfix(daily): Fix daily case
  MiniKita.xcodeproj/project.pbxproj
  MiniKita.xcodeproj/project.xcworkspace/xcuserdata/anjarharimurti.xcuserdatad/UserInterfaceState.xcuserstate
  MiniKita.xcodeproj/xcuserdata/anjarharimurti.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  MiniKita/Assets.xcassets/AppIcon.appiconset/appIcon.png
  MiniKita/View/Dashboard/Dashboard.swift
Labels: bug
